server:
  port: 8078

spring:
  application:
    name: cloud-order-service
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181
  datasource:
    #    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root