server:
  port: 8001
spring:
  application:
    name: cloud-payment-service

  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root

#  #P94 需要的配置
#  zipkin:
#    base-url: http://localhost:9411
#  sleuth:
#    sampler:
#      probability: 1  #采样率值介于0-1之间,1标识全部采集

mybatis:
  mapper-locations: classpath:mapper/*.xml #src\main\resources\mapper
  #所有entity别名类所在包
  type-aliases-package: com.atguigu.springcloud.entities

debug: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
  instance:
    instance-id: payment8001
    prefer-ip-address: true
