server:
  port: 8001
spring:
  application:
    name: cloud-payment-service-hystrix
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka #,http://localhost:7002/eureka

debug: true
